# Generated by Django 5.1.7 on 2025-03-31 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_lost', models.DateField(blank=True, null=True)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('contact_info', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=5)),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
